In [9]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from IPython.display import display, Markdown, Latex
from sklearn.datasets import make_blobs
from matplotlib.widgets import Slider
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [13]:
def my_softmax(z):
    ez = np.exp(z)              
    sm = ez/np.sum(ez)
    return(sm)

In [15]:
# make  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [17]:
preferred_model = Sequential(
    [ 
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'linear')   #<-- Note
    ]
)
preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  #<--from_logits = True informs loss fn that softmax operation should be included in loss calc
    optimizer=tf.keras.optimizers.Adam(0.001),
)

preferred_model.fit(
    X_train,y_train,
    epochs=10
)
        

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - loss: 1.3825 
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step - loss: 0.5552
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - loss: 0.3228
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - loss: 0.1810
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - loss: 0.1019
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - loss: 0.0744
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step - loss: 0.0637
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step - loss: 0.0638
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - loss: 0.0486
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step - loss: 0.0479


In [19]:
p_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step
two example output vectors:
 [[-1.2757691 -2.2585754  2.8145077 -0.6125014]
 [ 6.8539567  1.7810242 -4.021648  -5.59921  ]]
largest value 12.482929 smallest value -11.692125


In [21]:
sm_preferred = tf.nn.softmax(p_preferred).numpy() # use softmax if desired outputs are probabilities
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[1.5854944e-02 5.9338617e-03 9.4743478e-01 3.0776424e-02]
 [9.9375248e-01 6.2248912e-03 1.8795901e-05 3.8809367e-06]]
largest value 0.99999774 smallest value 3.958764e-11


In [23]:
for i in range(5): #to select most likely category, just find index of largest output
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-1.2757691 -2.2585754  2.8145077 -0.6125014], category: 2
[ 6.8539567  1.7810242 -4.021648  -5.59921  ], category: 0
[ 5.021754   1.5822915 -3.0259547 -4.4375477], category: 0
[-0.76684713  4.635124   -0.97406375 -0.86643964], category: 1
[ 0.73023856 -5.4981337   5.381753   -4.1522746 ], category: 2


In [25]:
%pwd


'/Users/harryfyjis-walker'